services:
  - type: web
    name: texas-holdem-pvp
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
